### ISSUE TITLE
Edit compatibility between Bot and Web

### ISSUE THREAD

**Issue by tescher** [BanklessDAO/bountybot-#45]
If a bounty is edited on the web, it doesn't redraw the canonical card on the Bot, in fact it errors out with an invalid activity. Should use the new refresh activity in #44

**Comment by tescher** [comment]
Here is the error it creates:

Processing edit activity event. Origination: bountyboardweb
default case: invalid activity
client sync error for for 62b0bdb0fc1eb68556e2d07c: 
{
  "indexMeta": true,
  "meta": {
    "name": "TypeError",
    "message": "Cannot read properties of undefined (reading 'bountyId')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'bountyId')\n    at handler (/home/tescher/bountybot-/dist/app/activity/bounty/Handler.js:21:59)\n    at changeStreamEventHandler (/home/tescher/bountybot-/dist/app/clientSync/ClientSync.js:109:37)\n    at ClientSync (/home/tescher/bountybot-/dist/app/clientSync/ClientSync.js:54:13)\n    at ChangeStream.<anonymous> (/home/tescher/bountybot-/dist/app/app.js:92:37)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
  }
}

**Comment by tescher** [comment]
Fixed in #66
